/**
 * Summary result types for the AI summary engine.
 * All types here operate on de-identified data — no PHI allowed.
 */

import type { AiProviderName, SummaryLanguage } from './ai-config.js';
import type { Bundle } from '../fhir/bundle.js';

/** Token usage statistics for a single AI call */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

/**
 * Raw AI provider response.
 * Content is de-identified — never contains PHI.
 */
export interface AiResponse {
  /** The generated text content */
  content: string;
  /** Token counts reported by the provider */
  tokenUsage: TokenUsage;
  /** Actual model used (may differ from requested if fallback occurred) */
  model: string;
  /** Why generation stopped: 'stop', 'max_tokens', 'error' */
  finishReason: 'stop' | 'max_tokens' | 'error';
}

/**
 * Summary for a single FHIR resource category (e.g. Conditions, Medications).
 * Content is de-identified — original patient identifiers have been replaced.
 */
export interface SectionSummary {
  /** Section name (e.g. 'Conditions', 'Medications', 'Allergies') */
  section: string;
  /** De-identified summary text generated by AI */
  content: string;
  /** Total tokens used for this section */
  tokenCount: number;
  /** Number of FHIR resources included in this section */
  resourceCount: number;
  /**
   * True khi provider dừng vì max_tokens — nội dung section có thể bị cắt giữa chừng.
   * Clinician-facing output PHẢI hiển thị cảnh báo khi flag này bật.
   */
  truncated?: boolean;
  /**
   * Resource types có trong bundle nhưng KHÔNG được map vào section nào —
   * surfaced để clinician biết dữ liệu nào bị loại khỏi summary (tránh hiểu lầm "không có dữ liệu").
   */
  excludedResourceTypes?: string[];
}

/**
 * Metadata describing how a patient summary was generated.
 */
export interface SummaryMetadata {
  /** ISO 8601 timestamp when summary was generated */
  generatedAt: string;
  /** AI provider used for primary generation */
  provider: AiProviderName;
  /** Actual model identifier used */
  model: string;
  /** Total tokens consumed across all sections + synthesis */
  totalTokens: number;
  /** Language of the generated summary */
  language: SummaryLanguage;
  /** True = data was de-identified before AI call (should always be true) */
  deidentified: boolean;
  /**
   * Disclaimer theo từng lần chạy — nêu rõ trạng thái ngày tháng trong output
   * (đã re-identify về ngày thật, hay vẫn shifted ±N ngày với multi-patient bundle).
   */
  disclaimer?: string;
}

/**
 * Complete patient summary with all sections and synthesized narrative.
 * All content is de-identified (or has been re-identified via shiftMap for dates).
 */
export interface PatientSummary {
  /** Individual section summaries (Conditions, Medications, etc.) */
  sections: SectionSummary[];
  /** Final synthesized narrative combining all sections */
  synthesis: string;
  /** Generation metadata for audit/billing */
  metadata: SummaryMetadata;
}

/**
 * A de-identified FHIR Bundle.
 * Patient identifiers have been hashed, dates shifted, names/contacts removed.
 * This type is a marker — structurally identical to Bundle but semantically safe for AI.
 */
export type DeidentifiedBundle = Bundle & {
  /** Marker property confirming de-identification was applied */
  readonly _deidentified: true;
};

/**
 * Maps patient ID hash → date shift offset in days.
 * Used to consistently shift all dates for a given patient, and to reverse-shift
 * in the final output when needed.
 */
export interface DateShiftMap {
  /** patientIdHash → offset in days (can be negative) */
  [patientIdHash: string]: number;
}
